"""
config.py — Acieral Kairos Bot

HARD_CONSTRAINTS: human-defined, never change without explicit sign-off.
DISCOVERED_PARAMS: populated by ml/config_generator.py after training — never hand-edit.
"""

HARD_CONSTRAINTS = {
    # Instruments
    "FOREX_PAIRS": ["EUR_USD", "GBP_USD", "AUD_USD", "USD_JPY", "USD_CHF"],
    "INDEX_INSTRUMENTS": ["SPX500_USD", "NAS100_USD", "DE30_EUR"],
    "ALL_INSTRUMENTS": ["EUR_USD", "GBP_USD", "AUD_USD", "USD_JPY", "USD_CHF",
                        "SPX500_USD", "NAS100_USD", "DE30_EUR"],

    # Account
    "ACCOUNT_CURRENCY": "GBP",
    "OANDA_ENVIRONMENT": "practice",

    # Risk
    "RISK_PER_TRADE": 0.0030,   # fallback default — live sizing uses RISK_TIERS
    "RISK_TIERS": [
        {"max_equity": 20000,        "risk_pct": 0.0050},
        {"max_equity": 50000,        "risk_pct": 0.0040},
        {"max_equity": 100000,       "risk_pct": 0.0030},
        {"max_equity": float("inf"), "risk_pct": 0.0020},
    ],
    "MAX_RISK_PER_TRADE_GBP": {
        "AUD_USD":    50,
        "EUR_USD":    50,
        "GBP_USD":    50,
        "USD_JPY":    50,
        "USD_CHF":    50,
        "SPX500_USD": 50,
        "NAS100_USD": 50,
        "DE30_EUR":   50,
    },
    "MAX_UNITS_PER_TRADE": {
        "AUD_USD":    9999999,
        "EUR_USD":    9999999,
        "GBP_USD":    9999999,
        "USD_JPY":    9999999,
        "USD_CHF":    9999999,
        "SPX500_USD": 5,
        "NAS100_USD": 2,
        "DE30_EUR":   2,
    },
    "MAX_TRADES_PER_INSTRUMENT_PER_DAY": 1,
    "MAX_OPEN_TRADES_FOREX": 5,
    "MAX_OPEN_TRADES_INDICES": 3,
    "MAX_OPEN_TRADES_TOTAL": 8,
    "DAILY_DRAWDOWN_KILL_PCT": 0.03,
    "REENTRY_COOLDOWN_HOURS": 2,
    "REENTRY_CONFIDENCE_FLOOR": 0.70,

    # Timing
    "FOREX_WEEKEND_CLOSE_UTC": "21:00",     # Friday

    # Index session close times (UTC) — hard EOD
    "INDEX_SESSION_CLOSE_UTC": {
        "SPX500_USD": "21:00",
        "NAS100_USD": "21:00",
        "DE30_EUR":   "16:30",
    },

    # Training
    "TRAINING_START": "2017-01-01",
    "HOLDOUT_START": "2024-01-01",
    "TRAINING_WINDOW_MONTHS": 18,
    "VALIDATION_MONTHS": 3,
    "WALKFORWARD_RETRAIN_DAYS": 20,

    # Backtest
    "BACKTEST_SL_ATR_MULT": 1.5,

    # Quote types (for position sizing)
    "INSTRUMENT_QUOTE_TYPE": {
        "EUR_USD": "usd_quote",
        "GBP_USD": "usd_quote",
        "AUD_USD": "usd_quote",
        "USD_JPY": "usd_base",
        "USD_CHF": "usd_base",
        "SPX500_USD": "usd_index",
        "NAS100_USD": "usd_index",
        "DE30_EUR":   "eur_index",
    },
}

# Populated by ml/config_generator.py after training — never hand-edit
DISCOVERED_PARAMS = {
    'ACTIVE_INSTRUMENTS': [
        'EUR_USD',
        'GBP_USD',
        'AUD_USD',
        'USD_JPY',
        'USD_CHF',
        'SPX500_USD',
        'NAS100_USD',
        'DE30_EUR',
    ],
    'INSTRUMENT_PARAMS': {
        'EUR_USD': {
            'N': 6,
            'T': 0.0005,
            'trail_atr_mult': 3.0,
            'exit_threshold': 0.35,
            'entry_model': 'ml/models/entry_EUR_USD.pkl',
            'exit_model': 'ml/models/exit_EUR_USD.pkl',
            'holdout_sharpe': 11.7439,
            'holdout_max_dd': 0.0051,
            'holdout_win_rate': 0.8367,
            'holdout_pnl_gbp': 30652.64,
        },
        'GBP_USD': {
            'N': 8,
            'T': 0.0005,
            'trail_atr_mult': 2.5,
            'exit_threshold': 0.3,
            'entry_model': 'ml/models/entry_GBP_USD.pkl',
            'exit_model': 'ml/models/exit_GBP_USD.pkl',
            'holdout_sharpe': 12.6011,
            'holdout_max_dd': 0.0039,
            'holdout_win_rate': 0.8174,
            'holdout_pnl_gbp': 33594.53,
        },
        'AUD_USD': {
            'N': 8,
            'T': 0.0005,
            'trail_atr_mult': 2.0,
            'exit_threshold': 0.3,
            'entry_model': 'ml/models/entry_AUD_USD.pkl',
            'exit_model': 'ml/models/exit_AUD_USD.pkl',
            'holdout_sharpe': 13.0543,
            'holdout_max_dd': 0.0076,
            'holdout_win_rate': 0.8474,
            'holdout_pnl_gbp': 31293.84,
        },
        'USD_JPY': {
            'N': 8,
            'T': 0.0005,
            'trail_atr_mult': 2.0,
            'exit_threshold': 0.3,
            'entry_model': 'ml/models/entry_USD_JPY.pkl',
            'exit_model': 'ml/models/exit_USD_JPY.pkl',
            'holdout_sharpe': 12.4594,
            'holdout_max_dd': 0.0075,
            'holdout_win_rate': 0.8477,
            'holdout_pnl_gbp': 37989.5,
        },
        'USD_CHF': {
            'N': 8,
            'T': 0.0005,
            'trail_atr_mult': 3.0,
            'exit_threshold': 0.3,
            'entry_model': 'ml/models/entry_USD_CHF.pkl',
            'exit_model': 'ml/models/exit_USD_CHF.pkl',
            'holdout_sharpe': 13.1089,
            'holdout_max_dd': 0.0106,
            'holdout_win_rate': 0.8188,
            'holdout_pnl_gbp': 45767.59,
        },
        'SPX500_USD': {
            'N': 4,
            'T': 0.0005,
            'trail_atr_mult': 3.0,
            'exit_threshold': 0.3,
            'entry_model': 'ml/models/entry_SPX500_USD.pkl',
            'exit_model': 'ml/models/exit_SPX500_USD.pkl',
            'holdout_sharpe': 12.8705,
            'holdout_max_dd': 0.0095,
            'holdout_win_rate': 0.8352,
            'holdout_pnl_gbp': 37312.41,
        },
        'NAS100_USD': {
            'N': 4,
            'T': 0.0005,
            'trail_atr_mult': 3.0,
            'exit_threshold': 0.6,
            'entry_model': 'ml/models/entry_NAS100_USD.pkl',
            'exit_model': 'ml/models/exit_NAS100_USD.pkl',
            'holdout_sharpe': 9.9206,
            'holdout_max_dd': 0.0115,
            'holdout_win_rate': 0.7391,
            'holdout_pnl_gbp': 31123.79,
        },
        'DE30_EUR': {
            'N': 4,
            'T': 0.0005,
            'trail_atr_mult': 2.5,
            'exit_threshold': 0.3,
            'entry_model': 'ml/models/entry_DE30_EUR.pkl',
            'exit_model': 'ml/models/exit_DE30_EUR.pkl',
            'holdout_sharpe': 15.9134,
            'holdout_max_dd': 0.006,
            'holdout_win_rate': 0.8257,
            'holdout_pnl_gbp': 35777.99,
        },
    },
    'CONFIDENCE_CURVE': {
        'EUR_USD': {
            0: 0.8094,
            1: 0.808,
            2: 0.8061,
            3: 0.8084,
            4: 0.8062,
            5: 0.8162,
            6: 0.8217,
            7: 0.8208,
            8: 0.8184,
            9: 0.8204,
            10: 0.8234,
            11: 0.8261,
            12: 0.8251,
            13: 0.8238,
            14: 0.8231,
            15: 0.818,
            16: 0.8111,
            17: 0.8151,
            18: 0.8215,
            19: 0.8215,
            20: 0.8215,
            21: 0.8326,
            22: 0.8283,
            23: 0.8215,
        },
        'GBP_USD': {
            0: 0.7624,
            1: 0.7654,
            2: 0.7629,
            3: 0.7515,
            4: 0.7649,
            5: 0.7888,
            6: 0.8077,
            7: 0.8082,
            8: 0.8004,
            9: 0.8064,
            10: 0.8066,
            11: 0.7989,
            12: 0.7958,
            13: 0.7923,
            14: 0.7855,
            15: 0.7657,
            16: 0.7659,
            17: 0.7641,
            18: 0.7944,
            19: 0.7944,
            20: 0.7944,
            21: 0.8056,
            22: 0.7948,
            23: 0.7944,
        },
        'AUD_USD': {
            0: 0.7917,
            1: 0.7783,
            2: 0.7625,
            3: 0.7618,
            4: 0.7501,
            5: 0.7803,
            6: 0.7917,
            7: 0.7895,
            8: 0.7833,
            9: 0.7923,
            10: 0.7907,
            11: 0.7914,
            12: 0.7877,
            13: 0.7806,
            14: 0.7869,
            15: 0.7631,
            16: 0.7474,
            17: 0.7447,
            18: 0.7872,
            19: 0.7872,
            20: 0.7872,
            21: 0.8119,
            22: 0.8063,
            23: 0.7872,
        },
        'USD_JPY': {
            0: 0.7688,
            1: 0.7476,
            2: 0.748,
            3: 0.7461,
            4: 0.736,
            5: 0.7539,
            6: 0.7856,
            7: 0.7874,
            8: 0.7738,
            9: 0.7828,
            10: 0.7867,
            11: 0.7898,
            12: 0.7849,
            13: 0.782,
            14: 0.7797,
            15: 0.7382,
            16: 0.713,
            17: 0.7288,
            18: 0.7572,
            19: 0.7773,
            20: 0.7773,
            21: 0.8101,
            22: 0.7917,
            23: 0.7773,
        },
        'USD_CHF': {
            0: 0.7569,
            1: 0.7574,
            2: 0.7582,
            3: 0.7463,
            4: 0.7357,
            5: 0.7871,
            6: 0.8024,
            7: 0.8048,
            8: 0.7984,
            9: 0.8059,
            10: 0.8065,
            11: 0.8067,
            12: 0.7978,
            13: 0.7926,
            14: 0.7867,
            15: 0.7798,
            16: 0.747,
            17: 0.7941,
            18: 0.7941,
            19: 0.7941,
            20: 0.7941,
            21: 0.8147,
            22: 0.8004,
            23: 0.7941,
        },
        'SPX500_USD': {
            0: 0.7722,
            1: 0.7908,
            2: 0.7908,
            3: 0.7487,
            4: 0.7236,
            5: 0.7453,
            6: 0.7643,
            7: 0.7502,
            8: 0.7165,
            9: 0.7559,
            10: 0.7735,
            11: 0.7964,
            12: 0.7949,
            13: 0.8083,
            14: 0.8107,
            15: 0.8036,
            16: 0.7976,
            17: 0.7913,
            18: 0.803,
            19: 0.7908,
            20: 0.7908,
            21: 0.7908,
            22: 0.7908,
            23: 0.7908,
        },
        'NAS100_USD': {
            0: 0.7041,
            1: 0.7692,
            2: 0.7692,
            3: 0.7692,
            4: 0.6429,
            5: 0.6349,
            6: 0.6826,
            7: 0.6624,
            8: 0.6382,
            9: 0.7062,
            10: 0.7507,
            11: 0.7787,
            12: 0.7885,
            13: 0.8006,
            14: 0.8007,
            15: 0.7884,
            16: 0.7698,
            17: 0.7544,
            18: 0.759,
            19: 0.7692,
            20: 0.7692,
            21: 0.7692,
            22: 0.7692,
            23: 0.7692,
        },
        'DE30_EUR': {
            0: 0.6343,
            1: 0.7522,
            2: 0.6307,
            3: 0.6399,
            4: 0.72,
            5: 0.7551,
            6: 0.7811,
            7: 0.7783,
            8: 0.7444,
            9: 0.7378,
            10: 0.7505,
            11: 0.7627,
            12: 0.7573,
            13: 0.7376,
            14: 0.7522,
            15: 0.7522,
            16: 0.7522,
            17: 0.7522,
            18: 0.7522,
            19: 0.7522,
            20: 0.7522,
            21: 0.7522,
            22: 0.7522,
            23: 0.7522,
        },
    },
    'FEATURE_IMPORTANCE': {
        'EUR_USD': [
            'session_ny',
            'd1_low_dist_atr',
            'day_of_week',
            'd1_high_dist_atr',
            'minutes_since_midnight',
            'hour_utc',
            'bull_candle_count',
            'bear_candle_count',
            'session_london',
            'close_lag_1',
            'day_low_dist_atr',
            'day_high_dist_atr',
            'session_asian',
            'atr_ratio_delta',
            'day_displacement_atr',
            'close_lag_2',
            'h4_ema20_slope',
            'rsi_div_bear',
            'w1_low_dist_atr',
            'session_overlap',
            'range_vs_atr_5',
            'fvg_stacked_bear',
            'w1_high_dist_atr',
            'd1_fvg_bull_exists',
            'macd_hist',
            'h4_close_vs_ema20',
            'swing_high_dist_atr',
            'swing_low_dist_atr',
            'd1_fvg_bear_exists',
            'bars_since_swing_high',
            'd1_ema20_slope',
            'h4_fvg_bear_exists',
            'roc_10',
            'h4_fvg_bull_exists',
            'adx_14',
            'd1_close_vs_ema20',
            'atr_ratio',
            'roc_4',
            'close_lag_3',
            'candle_body_ratio',
            'rsi_14_delta_3',
            'macd_hist_delta',
            'fvg_bear_exists',
            'd1_fvg_dist_atr',
            'fvg_bear_size_atr',
            'sweep_high_mag_atr',
            'fvg_bear_dist_atr',
            'h4_swing_bias',
            'body_ratio_lag_1',
            'adx_delta',
            'h4_fvg_dist_atr',
            'swing_swept_low',
            'rsi_14',
            'close_lag_4',
            'body_ratio_lag_3',
            'bars_since_swing_low',
            'fvg_bull_age',
            'fvg_bull_size_atr',
            'wick_lower_ratio',
            'structure_bias',
            'fvg_bull_fill_pct',
            'fvg_bear_age',
            'd1_swing_bias',
            'fvg_bull_dist_atr',
            'wick_lower_lag_1',
            'wick_upper_lag_1',
            'fvg_bear_fill_pct',
            'hours_since_session_open',
            'body_ratio_lag_2',
            'sweep_low_mag_atr',
            'wick_upper_ratio',
            'htf_alignment',
            'rsi_div_bull',
            'fvg_stacked_bull',
            'fvg_bull_exists',
            'is_london_first_3h',
            'is_ny_first_3h',
            'swing_swept_high',
            'vix_close',
            'vix_delta_1',
            'spy_volume_ratio',
        ],
        'GBP_USD': [
            'session_ny',
            'd1_low_dist_atr',
            'd1_high_dist_atr',
            'day_of_week',
            'bear_candle_count',
            'bull_candle_count',
            'hour_utc',
            'minutes_since_midnight',
            'close_lag_1',
            'hours_since_session_open',
            'day_high_dist_atr',
            'h4_fvg_bull_exists',
            'd1_fvg_bear_exists',
            'h4_fvg_bear_exists',
            'atr_ratio_delta',
            'day_low_dist_atr',
            'close_lag_2',
            'w1_low_dist_atr',
            'h4_ema20_slope',
            'w1_high_dist_atr',
            'macd_hist',
            'range_vs_atr_5',
            'h4_close_vs_ema20',
            'fvg_bear_exists',
            'fvg_bull_fill_pct',
            'rsi_14_delta_3',
            'bars_since_swing_high',
            'day_displacement_atr',
            'bars_since_swing_low',
            'roc_10',
            'rsi_14',
            'adx_delta',
            'swing_low_dist_atr',
            'swing_swept_high',
            'd1_ema20_slope',
            'session_overlap',
            'macd_hist_delta',
            'close_lag_3',
            'close_lag_4',
            'adx_14',
            'atr_ratio',
            'fvg_bear_age',
            'swing_high_dist_atr',
            'd1_close_vs_ema20',
            'sweep_low_mag_atr',
            'is_london_first_3h',
            'session_asian',
            'is_ny_first_3h',
            'sweep_high_mag_atr',
            'h4_fvg_dist_atr',
            'wick_upper_ratio',
            'swing_swept_low',
            'fvg_bear_fill_pct',
            'candle_body_ratio',
            'h4_swing_bias',
            'roc_4',
            'rsi_div_bear',
            'body_ratio_lag_1',
            'wick_lower_ratio',
            'fvg_bear_dist_atr',
            'd1_swing_bias',
            'fvg_bear_size_atr',
            'body_ratio_lag_3',
            'fvg_bull_dist_atr',
            'wick_lower_lag_1',
            'htf_alignment',
            'body_ratio_lag_2',
            'd1_fvg_dist_atr',
            'wick_upper_lag_1',
            'structure_bias',
            'fvg_bull_size_atr',
            'fvg_bull_age',
            'fvg_stacked_bull',
            'd1_fvg_bull_exists',
            'session_london',
            'rsi_div_bull',
            'fvg_stacked_bear',
            'fvg_bull_exists',
            'vix_close',
            'vix_delta_1',
            'spy_volume_ratio',
        ],
        'AUD_USD': [
            'd1_low_dist_atr',
            'day_of_week',
            'bear_candle_count',
            'd1_high_dist_atr',
            'bull_candle_count',
            'minutes_since_midnight',
            'session_london',
            'hour_utc',
            'close_lag_1',
            'session_ny',
            'day_high_dist_atr',
            'day_low_dist_atr',
            'day_displacement_atr',
            'h4_ema20_slope',
            'close_lag_2',
            'w1_low_dist_atr',
            'w1_high_dist_atr',
            'macd_hist',
            'swing_high_dist_atr',
            'h4_fvg_bull_exists',
            'wick_lower_ratio',
            'swing_low_dist_atr',
            'fvg_stacked_bear',
            'rsi_14_delta_3',
            'rsi_div_bull',
            'h4_fvg_bear_exists',
            'bars_since_swing_low',
            'range_vs_atr_5',
            'close_lag_3',
            'hours_since_session_open',
            'h4_close_vs_ema20',
            'atr_ratio_delta',
            'd1_ema20_slope',
            'close_lag_4',
            'roc_10',
            'atr_ratio',
            'macd_hist_delta',
            'roc_4',
            'h4_fvg_dist_atr',
            'd1_fvg_bull_exists',
            'd1_fvg_bear_exists',
            'swing_swept_low',
            'fvg_bull_size_atr',
            'fvg_bear_size_atr',
            'structure_bias',
            'fvg_bear_dist_atr',
            'bars_since_swing_high',
            'fvg_bull_age',
            'fvg_bear_fill_pct',
            'body_ratio_lag_1',
            'd1_close_vs_ema20',
            'h4_swing_bias',
            'sweep_low_mag_atr',
            'd1_fvg_dist_atr',
            'wick_lower_lag_1',
            'rsi_14',
            'd1_swing_bias',
            'candle_body_ratio',
            'wick_upper_lag_1',
            'fvg_bull_dist_atr',
            'fvg_bull_fill_pct',
            'wick_upper_ratio',
            'body_ratio_lag_2',
            'sweep_high_mag_atr',
            'adx_delta',
            'adx_14',
            'body_ratio_lag_3',
            'session_asian',
            'is_ny_first_3h',
            'session_overlap',
            'fvg_stacked_bull',
            'fvg_bear_age',
            'rsi_div_bear',
            'is_london_first_3h',
            'htf_alignment',
            'swing_swept_high',
            'fvg_bear_exists',
            'fvg_bull_exists',
            'vix_close',
            'vix_delta_1',
            'spy_volume_ratio',
        ],
        'USD_JPY': [
            'session_ny',
            'd1_low_dist_atr',
            'day_of_week',
            'd1_high_dist_atr',
            'bull_candle_count',
            'bear_candle_count',
            'minutes_since_midnight',
            'session_london',
            'close_lag_1',
            'hour_utc',
            'day_displacement_atr',
            'day_high_dist_atr',
            'day_low_dist_atr',
            'close_lag_2',
            'h4_fvg_bear_exists',
            'h4_ema20_slope',
            'fvg_bull_exists',
            'close_lag_3',
            'swing_low_dist_atr',
            'w1_high_dist_atr',
            'w1_low_dist_atr',
            'rsi_14_delta_3',
            'hours_since_session_open',
            'h4_close_vs_ema20',
            'swing_high_dist_atr',
            'bars_since_swing_high',
            'h4_fvg_bull_exists',
            'macd_hist',
            'atr_ratio_delta',
            'close_lag_4',
            'fvg_stacked_bull',
            'session_asian',
            'roc_10',
            'd1_fvg_bear_exists',
            'd1_ema20_slope',
            'atr_ratio',
            'fvg_bull_size_atr',
            'range_vs_atr_5',
            'session_overlap',
            'bars_since_swing_low',
            'macd_hist_delta',
            'd1_fvg_bull_exists',
            'd1_swing_bias',
            'candle_body_ratio',
            'd1_close_vs_ema20',
            'adx_delta',
            'fvg_bull_fill_pct',
            'is_ny_first_3h',
            'swing_swept_low',
            'roc_4',
            'wick_lower_ratio',
            'body_ratio_lag_1',
            'adx_14',
            'h4_fvg_dist_atr',
            'body_ratio_lag_3',
            'wick_upper_lag_1',
            'fvg_bull_dist_atr',
            'sweep_high_mag_atr',
            'rsi_14',
            'fvg_bear_fill_pct',
            'wick_lower_lag_1',
            'd1_fvg_dist_atr',
            'fvg_bear_size_atr',
            'fvg_bear_dist_atr',
            'structure_bias',
            'h4_swing_bias',
            'wick_upper_ratio',
            'body_ratio_lag_2',
            'fvg_bear_age',
            'fvg_bull_age',
            'sweep_low_mag_atr',
            'rsi_div_bear',
            'rsi_div_bull',
            'swing_swept_high',
            'fvg_bear_exists',
            'is_london_first_3h',
            'fvg_stacked_bear',
            'htf_alignment',
            'vix_close',
            'vix_delta_1',
            'spy_volume_ratio',
        ],
        'USD_CHF': [
            'session_ny',
            'd1_low_dist_atr',
            'd1_high_dist_atr',
            'day_of_week',
            'bear_candle_count',
            'minutes_since_midnight',
            'bull_candle_count',
            'session_overlap',
            'session_london',
            'hour_utc',
            'close_lag_1',
            'day_high_dist_atr',
            'hours_since_session_open',
            'is_ny_first_3h',
            'day_low_dist_atr',
            'close_lag_2',
            'fvg_stacked_bear',
            'day_displacement_atr',
            'h4_ema20_slope',
            'h4_fvg_bear_exists',
            'w1_low_dist_atr',
            'atr_ratio_delta',
            'w1_high_dist_atr',
            'h4_close_vs_ema20',
            'close_lag_3',
            'range_vs_atr_5',
            'swing_low_dist_atr',
            'macd_hist',
            'bars_since_swing_high',
            'bars_since_swing_low',
            'swing_high_dist_atr',
            'atr_ratio',
            'rsi_14_delta_3',
            'd1_fvg_dist_atr',
            'd1_ema20_slope',
            'session_asian',
            'roc_10',
            'structure_bias',
            'macd_hist_delta',
            'd1_fvg_bear_exists',
            'htf_alignment',
            'd1_close_vs_ema20',
            'adx_delta',
            'h4_fvg_bull_exists',
            'h4_swing_bias',
            'rsi_14',
            'wick_lower_lag_1',
            'adx_14',
            'fvg_bull_exists',
            'is_london_first_3h',
            'sweep_low_mag_atr',
            'body_ratio_lag_3',
            'candle_body_ratio',
            'h4_fvg_dist_atr',
            'fvg_bull_fill_pct',
            'roc_4',
            'close_lag_4',
            'wick_upper_lag_1',
            'body_ratio_lag_1',
            'fvg_bear_fill_pct',
            'fvg_stacked_bull',
            'body_ratio_lag_2',
            'wick_lower_ratio',
            'wick_upper_ratio',
            'fvg_bull_age',
            'fvg_bull_size_atr',
            'fvg_bear_exists',
            'd1_swing_bias',
            'fvg_bear_dist_atr',
            'fvg_bull_dist_atr',
            'swing_swept_high',
            'fvg_bear_size_atr',
            'd1_fvg_bull_exists',
            'rsi_div_bull',
            'rsi_div_bear',
            'sweep_high_mag_atr',
            'fvg_bear_age',
            'swing_swept_low',
            'vix_close',
            'vix_delta_1',
            'spy_volume_ratio',
        ],
        'SPX500_USD': [
            'session_london',
            'session_asian',
            'd1_high_dist_atr',
            'd1_low_dist_atr',
            'h4_fvg_bull_exists',
            'vix_delta_1',
            'hours_since_session_open',
            'minutes_since_midnight',
            'hour_utc',
            'close_lag_1',
            'session_ny',
            'day_high_dist_atr',
            'h4_ema20_slope',
            'day_displacement_atr',
            'swing_high_dist_atr',
            'day_low_dist_atr',
            'is_london_first_3h',
            'w1_high_dist_atr',
            'fvg_bear_exists',
            'h4_close_vs_ema20',
            'spy_volume_ratio',
            'h4_fvg_bear_exists',
            'range_vs_atr_5',
            'close_lag_2',
            'rsi_div_bear',
            'w1_low_dist_atr',
            'swing_low_dist_atr',
            'close_lag_3',
            'vix_close',
            'fvg_bear_size_atr',
            'bear_candle_count',
            'bull_candle_count',
            'roc_10',
            'atr_ratio_delta',
            'sweep_high_mag_atr',
            'macd_hist_delta',
            'bars_since_swing_high',
            'macd_hist',
            'h4_fvg_dist_atr',
            'day_of_week',
            'fvg_bull_dist_atr',
            'close_lag_4',
            'd1_fvg_bull_exists',
            'bars_since_swing_low',
            'atr_ratio',
            'fvg_bull_size_atr',
            'd1_ema20_slope',
            'rsi_14',
            'roc_4',
            'fvg_bear_dist_atr',
            'd1_close_vs_ema20',
            'd1_swing_bias',
            'rsi_14_delta_3',
            'd1_fvg_dist_atr',
            'fvg_bear_age',
            'body_ratio_lag_1',
            'body_ratio_lag_2',
            'candle_body_ratio',
            'h4_swing_bias',
            'wick_lower_ratio',
            'wick_upper_ratio',
            'adx_delta',
            'sweep_low_mag_atr',
            'body_ratio_lag_3',
            'htf_alignment',
            'is_ny_first_3h',
            'wick_lower_lag_1',
            'adx_14',
            'fvg_bear_fill_pct',
            'wick_upper_lag_1',
            'fvg_bull_fill_pct',
            'session_overlap',
            'fvg_stacked_bull',
            'fvg_stacked_bear',
            'd1_fvg_bear_exists',
            'structure_bias',
            'fvg_bull_age',
            'swing_swept_high',
            'fvg_bull_exists',
            'rsi_div_bull',
            'swing_swept_low',
        ],
        'NAS100_USD': [
            'session_london',
            'session_asian',
            'd1_high_dist_atr',
            'd1_low_dist_atr',
            'hours_since_session_open',
            'h4_fvg_bull_exists',
            'minutes_since_midnight',
            'close_lag_1',
            'vix_delta_1',
            'hour_utc',
            'day_high_dist_atr',
            'day_displacement_atr',
            'h4_fvg_bear_exists',
            'is_london_first_3h',
            'day_low_dist_atr',
            'range_vs_atr_5',
            'w1_high_dist_atr',
            'fvg_stacked_bear',
            'w1_low_dist_atr',
            'bear_candle_count',
            'swing_high_dist_atr',
            'swing_low_dist_atr',
            'h4_close_vs_ema20',
            'h4_ema20_slope',
            'session_overlap',
            'atr_ratio_delta',
            'spy_volume_ratio',
            'fvg_stacked_bull',
            'macd_hist',
            'roc_10',
            'close_lag_3',
            'vix_close',
            'h4_fvg_dist_atr',
            'sweep_high_mag_atr',
            'roc_4',
            'd1_fvg_bull_exists',
            'close_lag_2',
            'd1_swing_bias',
            'd1_ema20_slope',
            'bull_candle_count',
            'atr_ratio',
            'fvg_bear_size_atr',
            'bars_since_swing_high',
            'day_of_week',
            'd1_close_vs_ema20',
            'rsi_14',
            'body_ratio_lag_1',
            'close_lag_4',
            'bars_since_swing_low',
            'fvg_bear_fill_pct',
            'structure_bias',
            'body_ratio_lag_3',
            'rsi_14_delta_3',
            'macd_hist_delta',
            'fvg_bull_dist_atr',
            'wick_upper_lag_1',
            'rsi_div_bull',
            'candle_body_ratio',
            'adx_14',
            'sweep_low_mag_atr',
            'wick_lower_ratio',
            'wick_lower_lag_1',
            'wick_upper_ratio',
            'swing_swept_high',
            'fvg_bear_dist_atr',
            'rsi_div_bear',
            'd1_fvg_dist_atr',
            'adx_delta',
            'body_ratio_lag_2',
            'fvg_bull_fill_pct',
            'fvg_bull_size_atr',
            'h4_swing_bias',
            'fvg_bear_age',
            'd1_fvg_bear_exists',
            'fvg_bull_age',
            'is_ny_first_3h',
            'session_ny',
            'htf_alignment',
            'fvg_bull_exists',
            'fvg_bear_exists',
            'swing_swept_low',
        ],
        'DE30_EUR': [
            'session_ny',
            'session_london',
            'is_ny_first_3h',
            'd1_low_dist_atr',
            'minutes_since_midnight',
            'd1_high_dist_atr',
            'hour_utc',
            'session_asian',
            'h4_fvg_bull_exists',
            'day_low_dist_atr',
            'day_high_dist_atr',
            'close_lag_1',
            'hours_since_session_open',
            'w1_low_dist_atr',
            'd1_fvg_bull_exists',
            'bear_candle_count',
            'h4_ema20_slope',
            'w1_high_dist_atr',
            'h4_close_vs_ema20',
            'range_vs_atr_5',
            'close_lag_2',
            'h4_fvg_bear_exists',
            'htf_alignment',
            'vix_close',
            'day_displacement_atr',
            'vix_delta_1',
            'roc_4',
            'bull_candle_count',
            'close_lag_4',
            'swing_high_dist_atr',
            'd1_swing_bias',
            'is_london_first_3h',
            'macd_hist',
            'spy_volume_ratio',
            'close_lag_3',
            'h4_fvg_dist_atr',
            'rsi_14_delta_3',
            'atr_ratio_delta',
            'wick_upper_lag_1',
            'atr_ratio',
            'fvg_bull_age',
            'd1_ema20_slope',
            'roc_10',
            'body_ratio_lag_3',
            'rsi_14',
            'macd_hist_delta',
            'bars_since_swing_high',
            'day_of_week',
            'swing_low_dist_atr',
            'h4_swing_bias',
            'd1_fvg_dist_atr',
            'd1_close_vs_ema20',
            'fvg_bear_size_atr',
            'bars_since_swing_low',
            'adx_delta',
            'fvg_bull_dist_atr',
            'sweep_high_mag_atr',
            'wick_lower_lag_1',
            'sweep_low_mag_atr',
            'body_ratio_lag_1',
            'adx_14',
            'wick_lower_ratio',
            'structure_bias',
            'fvg_stacked_bear',
            'candle_body_ratio',
            'fvg_stacked_bull',
            'fvg_bear_age',
            'fvg_bear_dist_atr',
            'body_ratio_lag_2',
            'wick_upper_ratio',
            'd1_fvg_bear_exists',
            'fvg_bull_size_atr',
            'fvg_bull_fill_pct',
            'rsi_div_bull',
            'rsi_div_bear',
            'swing_swept_high',
            'fvg_bear_fill_pct',
            'session_overlap',
            'swing_swept_low',
            'fvg_bear_exists',
            'fvg_bull_exists',
        ],
    },
    'GLOBAL_FEATURE_RANKING': [
        'session_ny',
        'session_london',
        'd1_low_dist_atr',
        'd1_high_dist_atr',
        'session_asian',
        'day_of_week',
        'minutes_since_midnight',
        'hour_utc',
        'bear_candle_count',
        'bull_candle_count',
        'close_lag_1',
        'day_high_dist_atr',
        'hours_since_session_open',
        'h4_fvg_bull_exists',
        'is_ny_first_3h',
        'day_low_dist_atr',
        'day_displacement_atr',
        'close_lag_2',
        'h4_ema20_slope',
        'h4_fvg_bear_exists',
        'w1_low_dist_atr',
        'session_overlap',
        'w1_high_dist_atr',
        'atr_ratio_delta',
        'h4_close_vs_ema20',
        'range_vs_atr_5',
        'swing_high_dist_atr',
        'macd_hist',
        'swing_low_dist_atr',
        'close_lag_3',
        'd1_fvg_bear_exists',
        'roc_10',
        'rsi_14_delta_3',
        'bars_since_swing_high',
        'fvg_stacked_bear',
        'd1_ema20_slope',
        'atr_ratio',
        'd1_fvg_bull_exists',
        'close_lag_4',
        'bars_since_swing_low',
        'macd_hist_delta',
        'is_london_first_3h',
        'h4_fvg_dist_atr',
        'roc_4',
        'd1_close_vs_ema20',
        'vix_delta_1',
        'rsi_14',
        'd1_swing_bias',
        'wick_lower_ratio',
        'sweep_high_mag_atr',
        'fvg_bear_size_atr',
        'adx_delta',
        'rsi_div_bear',
        'adx_14',
        'candle_body_ratio',
        'fvg_bull_fill_pct',
        'body_ratio_lag_1',
        'd1_fvg_dist_atr',
        'fvg_stacked_bull',
        'h4_swing_bias',
        'fvg_bull_size_atr',
        'body_ratio_lag_3',
        'fvg_bear_dist_atr',
        'fvg_bull_dist_atr',
        'structure_bias',
        'wick_upper_lag_1',
        'sweep_low_mag_atr',
        'wick_lower_lag_1',
        'fvg_bear_fill_pct',
        'wick_upper_ratio',
        'fvg_bull_age',
        'fvg_bear_age',
        'body_ratio_lag_2',
        'htf_alignment',
        'fvg_bear_exists',
        'rsi_div_bull',
        'swing_swept_low',
        'swing_swept_high',
        'fvg_bull_exists',
        'spy_volume_ratio',
        'vix_close',
    ],
    'GENERATED_AT': '2026-04-13T07:40:55.476950+00:00',
    'GENERATED_FROM': 'ml/config_generator.py',
}